#!/system/bin/sh

#
# NOTE: this script depends on samsung rild
#
#       ril.bt_macaddr is set by samsung rild
#
#       It can only be read after the initial boot has completed.
#       This is because init does update the property db in a way
#       that getprop can NOT read the updates until the boot
#       sequence has finished.
#

BTMAC=$(getprop ril.bt_macaddr)
if [ -n "$BTMAC" ]; then

  # write bluetooth mac
  echo -n $(echo $BTMAC | cut -f2 -d: | sed 's/\(..\)/\1:/g;s/:$//') > /data/.nvram_btmac
  chown bluetooth.bluetooth /data/.nvram_btmac
  chmod 0664 /data/.nvram_btmac

fi

# set path to bluetooth mac file
setprop ro.bt.bdaddr_path /data/.nvram_btmac
